### ISSUE TITLE
Adding the plugin causes a boot error - seems like it is not included with Roda?

### ISSUE THREAD

**Issue by andreimoment** [badosu/roda-http-auth#2]
Seems like Roda version 3.55.0 (released April 12 2022) framework cannot find the plugin. 

I looked in the gem's `plugins`  [folder](https://github.com/jeremyevans/roda/tree/master/lib/roda/plugins) and could not find a corresponding file.

Do I need to install this plugin separately as a gem somehow? Don't see this in the documentation - could you please provide some guidance?

Thank you.

The plugin was added like this:

```
class App < Roda
  plugin :json
  plugin :json_parser
  plugin :render, engine: 'slim', views: "app/views"
  plugin :http_auth
```

and caused this error:

```
Boot Error
Something went wrong while loading config.ru

LoadError: cannot load such file -- roda/plugins/http_auth
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/roda-3.55.0/lib/roda/plugins.rb:29:in `require'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/roda-3.55.0/lib/roda/plugins.rb:29:in `load_plugin'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/roda-3.55.0/lib/roda.rb:281:in `plugin'
/Users/username/Desktop/dev/ruby/appname/app/app.rb:12:in `<class:App>'
/Users/username/Desktop/dev/ruby/appname/app/app.rb:7:in `<top (required)>'
config.ru:1:in `require'
config.ru:1:in `block in inner_app'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
config.ru:1:in `new'
config.ru:1:in `inner_app'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:113:in `eval'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:113:in `inner_app'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:103:in `assemble_app'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:86:in `proceed_as_child'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:31:in `call!'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/loader.rb:18:in `call'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/shotgun-0.9.2/lib/shotgun/favicon.rb:12:in `call'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
/Users/username/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by andreimoment** [comment]
I realized this needs to be installed as a gem. Closing.

Added a pull request for updating the documentation.
